### ISSUE TITLE
Using text expansion snippets within list items produces additional tab spacing as a prefix to the snippet

### ISSUE THREAD

**Issue by julroger2013** [jglev/obsidian-paste-to-current-indentation#5]
if one uses a TextExpander (or similar text expansion app) snippet inside a nested, bulleted (or probably numbered, too) list item with the Paste to Current Indentation Plugin enabled, the snippet will be prefixed by a number of additional tab indentations equivalent to the current indentation level (e.g. there will be two extra tab spacings before the snippet if one uses text expansion inside a twice-nested list item). 

I deactivated all plugins to see where the issue was, and this only reappeared upon reactivating the Paste to Current Indentation Plugin. 

This was done on MacOS in the latest Insider Version of Obsidian with Live Preview activated.

**Comment by julroger2013** [comment]
Addendum: The issue only happens when using one of the Paste to Current Indentation Modes. Toggling to passthrough mode resolves the issue.

**Comment by jglev** [comment]
@julroger2013, thank you for reporting this! I actually just noticed this behavior myself yesterday -- it seems to happen not just when using a text expander, but when pasting in general.

I've just now released version [`2.0.1`](https://github.com/jglev/obsidian-paste-to-current-indentation/releases/tag/2.0.1), which I _think_ addresses the issue. Please do let me know if it's resolved!

I'm going to close this in the meantime, but 100% can re-open it if it turns out that the new version doesn't resolve the issue. Again, thank you!
